node('master') {
  stage('Workspace Cleanup') {
          deleteDir()
        }
  stage('Get Source Code from Git') {
        checkout([$class: 'GitSCM',
        branches: [[name: '*/master']],
        doGenerateSubmoduleConfigurations: false,
        extensions: [],
        submoduleCfg: [],
        userRemoteConfigs: [[url: 'https://github.com/zking2000/tw-code.git']]])
      }
}




